task :default => [:compile]

desc "Compile all *.tex files into pretty PDFs"
task :compile do
  sh 'rubber --force --inplace --pdf ./**/*.tex'
  Rake::Task["clean"].invoke
end

desc "Cleanup all the cruft that was generated by rubber"
task :clean do
  ["aux", "log", "dvi"].each do |ext|
    `rm ./**/*.#{ext}`
  end
end
